name: 4DNFIXP4QG5B_mggp_lcgp
seed: 67
dataset: 4DNFIXP4QG5B
output_dir: outputs/4DNFIXP4QG5B

preprocessing:
  mcool_path: /gladstone/engelhardt/lab/lchumpitaz/hi-c/mcools/4DNFIXP4QG5B.mcool
  resolution: 25000
  region: chr14
  balance: true
  contact_transform: log1p
  num_replicates: 1
  noise_level: 0.15
  groups_by: null
  chromhmm_bed: null
  chromhmm_states: null

model:
  n_components: 3
  E: 1
  prior: LCGP
  groups: true
  integrated_force: false
  sigma: 1.0
  jitter: 1.0e-05
  train_lengthscale: false
  lengthscale: 8.0
  noise: 0.1
  kernel: RBF
  local: true

training:
  max_iter: 20000
  learning_rate: 0.002
  optimizer: Adam
  device: gpu
  batch_size: null
  shuffle: true
